/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmpOperations;
import model.Employee;

/**
 *
 * @author Himanshu
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    boolean isPresent = false;
    EmpOperations empCrudOpertions;
    public SearchJPanel(EmpOperations empCrudOpertions) {
        initComponents();
        
        this.empCrudOpertions = empCrudOpertions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empDataTable = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmbSearch = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreate.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(102, 0, 0));
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("Fetch Employee Data");
        add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 1100, 31));

        empDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employeee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell phone Number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empDataTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 1100, 216));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 319, 90, 29));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 319, 90, 29));

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee Name", "Employee ID", "Employee Age", " " }));
        add(cmbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 56, 143, 35));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 56, 143, 35));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 56, 143, 35));
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 379, 268, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
           ArrayList<Employee> empList = empCrudOpertions.getEmpCrudOpertions();
   
   String cmbSrch = cmbSearch.getSelectedItem().toString();
   String cmbValue = txtSearch.getText();
   
    ArrayList<Employee> employeeList = new ArrayList<>();
    
    if (cmbSrch.equalsIgnoreCase("Employee Name"))
    {
        for (Employee employee : empList) {
                if (employee.getName().contains(cmbValue)) 
                {
                    employeeList.add(employee);
                    isPresent = true;
                }
            }
    }
    else if (cmbSrch.equalsIgnoreCase("Employee ID")) {
            for (Employee employee : empList) {

                if (cmbValue == employee.getEmpId()) 
                {
                    employeeList.add(employee);
                    isPresent = true;
                }
            }
        } 
    else if (cmbSrch.equals("Employee Age")) {
            for (Employee employee : empList) {

                if (Integer.parseInt(cmbValue) == employee.getAge()) {

                    employeeList.add(employee);
                    isPresent = true;
                }
            }
        }
   
    DefaultTableModel model = (DefaultTableModel) empDataTable.getModel();
        model.setRowCount(0);

        for (Employee emp : employeeList){
                    Object[] row = new Object[10];
                    row[0] = emp;
                    row[1] = emp.getEmpId();
                    row[2] = emp.getAge();
                    row[3] = emp.getGender();
                    row[4] = emp.getStartDate();
                    row[5] = emp.getLevel();
                    row[6] = emp.getTeamInfo();
                    row[7] = emp.getPosTitle();
                    row[8] = emp.getCellNum();
                    row[9] = emp.getEmailAdd();
                    model.addRow(row);
                    
                     Image img = Toolkit.getDefaultToolkit().createImage(emp.getPhoto());
        img = img.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(img);
        lblPhoto.setIcon(icon);
                    
                 if (isPresent == false) 
                 {
                    JOptionPane.showMessageDialog(null, "No Records found");
                    return;
                }                                         
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JTable empDataTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
